version: '3'
services:
  database:
    container_name: morning_wood_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
  client:
    container_name: morning_wood_client
    build:
      dockerfile: Dockerfile
      context: ./Morning-Wood-Client

volumes:
  dbdata:

